version: '3.8'

services:
  # Member 2: Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./reports:/app/reports
      - ./engines_manifest.yaml:/app/engines_manifest.yaml
      - /var/run/docker.sock:/var/run/docker.sock # Allows Backend to launch engines
    depends_on:
      - redis

  # Member 4: React UI
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  # Your Territory: Automation 
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine

volumes:
  jenkins_home: